name: Test
on: push
env:
  my-var: test
  my-number: 0
  my-boolean: true
jobs:
  Regression-Test-Stalkcd-Application:
    runs-on: ubuntu-latest
    steps:
      - name: Hello World
        run: echo Hello World
