name: Test
on: push
defaults:
  run:
    shell: sh
permissions:
  actions: write
  checks: write
  contents: read
  "id-token": read
concurrency:
  group: my-concurrency-group
  cancel-in-progress: false
jobs:
  Regression-Test-Stalkcd-Application:
    runs-on: ubuntu-latest
    steps:
      - name: Hello World
        run: echo Hello World
