name: Test
on: push
jobs:
  A_Job_With_Timeout:
    runs-on: ubuntu-latest
    needs:
      - first_need
      - second_need
    concurrency:
      cancel-in-progress: true
      group: the_job_concurrency_group
    steps:
      - name: Hello World
        run: echo Hello World