name: GitHub Actions Demo
on: [push]
jobs:
  Regression-Test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Build image locally
        run: docker build --target stalkcd-application --tag stalkcd-application:latest --file docker/Application.dockerfile .
      - name: Run Tests in image
        run: ls -la
      - name: Run Tests in image
        run: pwd
