name: StalkCd Application Tests
on: [push]
jobs:
  Regression-Test-Stalkcd-Application:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Build image locally
        run: docker build --target stalkcd-application --tag stalkcd-application:latest --file docker/Application.dockerfile .
      - name: Run tests in docker image
        run: docker run --rm -v "/home/runner/work/stalkcd/stalkcd/res:/usr/app/res" -v "/home/runner/work/stalkcd/stalkcd/src:/usr/app/src" stalkcd-application
